### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TotalVerb** [TotalVerb/puzzling#1]
Hi guys,

I think Yu Chen and Julian added some questions to this repo. I'd like to make it open-source. Can I have your permission to license this under, say, the MIT license?

Thanks in advance!

**Comment by samczsun** [comment]
:+1:

**Comment by JulianCO** [comment]
You have my permission (though I don't think I've actually made any changes)

**Comment by agapic** [comment]
go for it

**Comment by TotalVerb** [comment]
@icechen1

**Comment by yucombinator** [comment]
:+1:

**Comment by TotalVerb** [comment]
That's all. Thank you folks!
